version: "3.8"

services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker:latest-arm

    restart: always

    ports:
      - 8765:80

    volumes:
      - /data:/config

    environment:
      - TZ="Europe/Rome"
      - OOKLA_EULA_GDPR=true
      - AUTH=true

    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

    labels:
      - traefik.enable=true
      - traefik.http.routers.speedtest.rule=Host(`speedtest.example.com`)
      - traefik.http.routers.speedtest.entrypoints=websecure
      - traefik.http.routers.speedtest.tls.certresolver=myresolver
      - traefik.http.routers.speedtest.service=speedtest
      - traefik.http.services.speedtest.loadbalancer.server.port=80
