version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always

    security_opt:
      - no-new-privileges:true

    volumes:
      - ./localtime:/etc/localtime:ro
      - ./docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
      
    ports:
      - 9004:9000
